### ISSUE TITLE
CrashLoopBackOff when running Polaris Webhook in kind cluster

### ISSUE THREAD

**Issue by petermbenjamin** [reactiveops/polaris#95]
### Repro Steps

1. Install [`kind`](https://kind.sigs.k8s.io/)
1. Spin up a local, 2-node cluster: `kind create cluster --config=config.yaml && export KUBECONFIG=~/.kube/kind-config-kind`
1. Deploy Polaris Webhook: `kubectl apply -f https://raw.githubusercontent.com/reactiveops/polaris/master/deploy/webhook.yaml`
1. Describe Pod: `kubectl -n polaris describe pod polaris`

### Expected Behavior

Webhook pod should be in a good state and running.

### Actual Behavior

Pod goes into CrashLoopBackOff.

#### Screenshot
![Screen Shot 2019-05-17 at 1 48 22 AM](https://user-images.githubusercontent.com/6811830/57915807-62ac1780-7846-11e9-8330-730911f4c3e7.png)

#### Kind Cluster Configuration
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
```
